name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    permissions:
        actions: write
        contents: read
        # To report GitHub Actions status checks
        statuses: write
        checks: write
        pull-requests: write
        security-events: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
      -  name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Images login test
        run: docker info

      - name: Build Images
        run: docker build . -f Dockerfile -t nooboys/textt

      - name: Images list  
        run: docker images

      - name: Push Image
        run: docker push nooboys/textt

      - name: Build
        uses: docker/build-push-action@v5
        with:
            push: false
            load: true
            tags: nooboys/textt:${{ github.sha }}
      
      - name: Trivy Docker Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          ignore-unfixed: true
          image-ref: nooboys/textt:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results-docker.sarif'
        
      - name: Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-docker.sarif'
          category: docker  
